### ISSUE TITLE
Strip unused components from war3map.lua

### ISSUE THREAD

**Issue by Anachron** [cipherxof/wc3-ts-template#6]
I realized that the build script does not strip non-used components and just fills the `war3map.lua` with all the `w3ts` libs.

**Comment by cipherxof** [comment]
A workaround would be to import the classes you need directly from it's module instead of `w3ts`

For example instead of
```typescript
import { Trigger } from "w3ts";
```
you could do 
```
import { Trigger } from "node_modules/w3ts/src/handles/trigger";
```
Less than ideal but I am not sure of any Lua optimizer that can remove unused code. I assume it would be somewhat complicated to determine what is actually unused. I will look more into this issue, and maybe talk with the TSTL team and see if they have any ideas.
